version: 0.0
os: linux
files:
  - source: /
    destination: /root/dento-backend/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: script/update.sh
      timeout: 150
      runas: root
